### PR TITLE
Rainbow mode

### PR DESCRIPTION
**Pull request by daskygit**
add led power selection jumper raw/vcc
add led power switch circuit
added per key rgb
replaced ws2812b underglow with sk6803 mini-e
rotated all switches
rerouted pcb
add .gitignore
clean up backup files

### CODE REVIEW

**Comment by daskygit** [comment]
A couple more notes, I didn't tidy up the tracks too much as someone is likely to come along and do curved I imagine. Also I've not updated the PCBA files, I know @sadekbaroudi said they were happy to do a mini PR for it.

**Comment by sadekbaroudi** [comment]
Approved from my end! I'll do the PCBA changes after this is merged, before the next person goes.

**Review by sadekbaroudi — APPROVED** [review]
Looks good!

**Comment by daskygit** [comment]
Thanks.

**Pull request merged**
